// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Curso.Model.Models
{
    public partial class Hospedagem
    {
        public int Id { get; set; }
        public int IdPlanoHospedagem { get; set; }
        public int IdPet { get; set; }
        public DateTime? DataEntrada { get; set; }
        public DateTime? DataPrevistaSaida { get; set; }
        public DateTime? DataEfetivaSaida { get; set; }
        public int? QtdDiarias { get; set; }
        public decimal? ValorPrevisto { get; set; }
        public decimal? ValorReal { get; set; }
        public decimal? ValorAdiantamento { get; set; }
        public string Tratamento { get; set; }
        public string Fechado { get; set; }
        public string Observacao { get; set; }
    }
}