// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Curso.Model.Models
{
    public partial class Medicamentos
    {
        public int Id { get; set; }
        public int IdHospedagem { get; set; }
        public string Descricao { get; set; }
        public DateTime DataAplicacao { get; set; }
    }
}