// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Curso.Model.Models
{
    public partial class PlanoHospedagem
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public decimal? ValorDiaria { get; set; }
        public string Descricao { get; set; }
    }
}