// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Curso.Model.Models
{
    public partial class ServicoHospedagem
    {
        public int Id { get; set; }
        public int IdHospedagem { get; set; }
        public int IdServico { get; set; }
        public int? Qtd { get; set; }
        public decimal? ValorUnitario { get; set; }
        public decimal? ValorTotal { get; set; }
    }
}